init.d qserv functions are now compliant to LSB

diff --git a/admin/templates/server/etc/init.d/qserv-functions b/admin/templates/server/etc/init.d/qserv-functions
--- a/admin/templates/server/etc/init.d/qserv-functions
+++ b/admin/templates/server/etc/init.d/qserv-functions
@@ -3,7 +3,90 @@
 # Author: Fabrice Jammes <fabrice.jammes@in2p3.fr> (09.17.2013)
 #-------------------------------------------------------------------------------
 
-. /etc/rc.d/init.d/functions
+
+#
+# Use LSB init script functions for printing messages, if possible
+#
+lsb_functions="/lib/lsb/init-functions"
+if test -f $lsb_functions ; then
+  . $lsb_functions
+else
+  log_success_msg()
+  {
+    echo " SUCCESS! $@"
+  }
+  log_failure_msg()
+  {
+    echo " ERROR! $@"
+  }
+fi
+
+# Check if any of $pid (could be plural) are running
+checkpid() {
+    local i
+
+    for i in $* ; do
+        [ -d "/proc/$i" ] && return 0
+    done
+    return 1
+}
+
+# used for service launched in background (i.e. with "$cmd&" ) :
+# - wait for the service to create its pid file during $service_startup_timeout
+# - return success once pid file is created, failure otherwise
+wait_for_pid () {
+  verb="$1"
+  manager_pid="$2"  # process ID of the program operating on the pid-file
+  i=0
+  avoid_race_condition="by checking again"
+  while test $i -ne $service_startup_timeout ; do
+
+    case "$verb" in
+      'created')
+        # wait for a PID-file to pop into existence.
+        test -s $pidfile && i='' && break
+        ;;
+      'removed')
+        # wait for this PID-file to disappear
+        test ! -s $pidfile && i='' && break
+        ;;
+      *)
+        echo "wait_for_pid () usage: wait_for_pid created|removed manager_pid"
+        exit 1
+        ;;
+    esac
+
+    # if manager isn't running, then pid-file will never be updated
+    if test -n "$manager_pid"; then
+      if kill -0 "$manager_pid" 2>/dev/null; then
+        :  # the manager still runs
+      else
+        # The manager may have exited between the last pid-file check and now.
+        if test -n "$avoid_race_condition"; then
+          avoid_race_condition=""
+          continue  # Check again.
+        fi
+
+        # there's nothing that will affect the file.
+        log_failure_msg "Manager of pid-file quit without updating file."
+        return 1  # not waiting any more.
+      fi
+    fi
+
+    echo -n "."
+    i=`expr $i + 1`
+    sleep 1
+  done
+
+  if test -z "$i" ; then
+    # success
+    return 0
+  else
+    # failure
+    return 1
+  fi
+}
+
 
 start() {
 	local prog lockfile= pidfile= pid retval=2 cmd= timeout=0
@@ -37,33 +120,51 @@ start() {
 	fi
 
  	# check to see if it's already running
+ 	echo -n "Starting $prog : "
 	if [ -f ${pidfile} ]; then
-		action $"Starting $prog: (already up)" /bin/true
+                log_success_msg "(already up)" 
 		retval=0
 	else
-		if [ ${timeout} == 0 ]; then
-		     	daemon ${cmd}
-			retval=$?
-		else
-			eval ${cmd}
-			# TODO if no delay is needed, use daemon ?
-        		pid=$!
-			sleep ${timeout}
-			checkpid ${pid} && retval=0
-		fi
-		if [ ${retval} -eq 0 ]
-		then
-                        # Create pid file only if service hasn't done it itself
+            if [ ${timeout} == 0 ]; then 
+                start_mode='manage-pid'
+            else
+                start_mode='timeout'
+            fi
+            case "$start_mode" in
+                'manage-pid')
+                    # $prog manages its pidfile
+                    # inspired by mysqld
+                    eval ${cmd}
+                    pid=$!
+                    # Default value, in seconds, afterwhich the script should timeout waiting
+                    # for server start.
+                    service_startup_timeout=900
+                    wait_for_pid created $pid 
+                    retval=$?
+                    ;;
+                'timeout')
+                    # $prog doesn't manage its pidfile : weak
+                    # used by qserv-master
+                    eval ${cmd}
+                    pid=$!
+                    sleep ${timeout}
+                    checkpid ${pid} && retval=0
+                    # Create pid file only if service hasn't done it itself
+                    if [ ${retval} -eq 0 ]; then
                         if [ ! -f ${pidfile} ]; then
                             echo ${pid} > ${pidfile}
                         fi
+                    fi
+                    ;;
+            esac
 
-	    		touch ${lockfile}
-			action $"Starting $prog: " /bin/true
-		else
-			action $"Starting $prog: " /bin/false
-			echo $"See startup logfile : ${LOGFILE}"
-		fi
+	    if [ ${retval} -eq 0 ]; then
+	        touch ${lockfile}
+                log_success_msg
+	    else
+                log_failure_msg
+		echo $"See startup logfile : ${LOGFILE}"
+	    fi
 	fi
 	return ${retval}
 }
@@ -99,14 +200,16 @@ stop() {
 		pidfile=/var/run/${prog}.pid
 	fi
 
+        echo -n "Stopping $prog : "
         if [ ! -f "$pidfile" ]; then
 	    # not running; per LSB standards this is "ok"
-	    action $"Stopping $prog: (already down)" /bin/true
-	    return 0
-	fi
-	echo -n $"Stopping $prog: "
-	killproc -p ${pidfile} -d ${timeout} $prog
-	RETVAL=$?
-	echo
-        [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
+            log_failure_msg "PID file could not be found"
+	    retval=999
+        else	
+	    log_success_msg
+	    killproc -p ${pidfile} -d ${timeout} $prog
+	    retval=$?
+            [ ${retval} = 0 ] && rm -f ${lockfile} ${pidfile}
+        fi
+        return ${retval}
 }
